### PR TITLE
Fix LOCAL in Parrot mountlist

### LINKED ISSUE #2121: LOCAL access control in parrot's mountlists has no effect
We can either remove it in favor of --disable-filesystem, or make it work exactly as --disable-filesystem. 

I like the latter, as it shields a mountlist against services included when compiling parrot.

### PR DESCRIPTION
**Pull request by trshaffer**
The current path resolution code in Parrot seems to more or less ignore the `LOCAL` access control. This PR adds a new resolve outcome, `PFS_RESOLVE_LOCAL`, that causes subsequent opens to skip service lookup, forcing use of the local filesystem. Aside from that, this return code behaves almost the same as `PFS_RESOLVE_UNCHANGED`.

Fixes #2121

### CODE REVIEW

File: parrot/src/pfs_table.cc [hunk 1]
```diff
@@ -516,6 +516,7 @@ int pfs_table::resolve_name(int is_special_syscall, const char *cname, struct pf
 		char tmp[PFS_PATH_MAX];
 		path_split(pname->path,pname->service_name,tmp);
 		pname->service = pfs_service_lookup(pname->service_name);
+		if (result == PFS_RESOLVE_LOCAL) pname->service = NULL;
```
Comment (btovar) [inline parrot/src/pfs_table.cc]: Tim, please add { } to this 'if'.

**Comment by btovar** [comment]
It looks good to me.
